services:
 hadoop-namenode:
   image: apache/hadoop:3.4.1
   container_name: hadoop-namenode
   hostname: hadoop-namenode
   user: "root"
   restart: always
   platform: linux/amd64
   deploy:
     resources:
       limits:
         cpus: "1.0"   # Ограничение использования CPU
         memory: "2g"  # Ограничение использования RAM
   shm_size: 10G
   ports:
     - "9870:9870"  # HTTP-порт для Web UI HDFS NameNode
     - "9001:9001"  # RPC порт для запросов к NameNode
   volumes:
     - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
     - ./config/hdfs-site-namenode.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
     - ./namenode_entrypoint.sh:/namenode_entrypoint.sh
   entrypoint: ["/bin/bash", "/namenode_entrypoint.sh"]
   command: ["hdfs", "namenode"]


 hadoop-datanode-1:
   image: apache/hadoop:3.4.1
   container_name: hadoop-datanode-1
   hostname: hadoop-datanode-1
   user: "root"
   restart: always
   platform: linux/amd64
   deploy:
     resources:
       limits:
         cpus: "1.0"   # Ограничение использования CPU
         memory: "2g"  # Ограничение использования RAM
   shm_size: 10G
   depends_on:
     - hadoop-namenode
   ports:
     - "9864:9864"  # HTTP-порт для Web UI DataNode №1
     - "9970:9970"  # RPC порт для запросов от NameNode
   volumes:
     - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
     - ./config/hdfs-site-datanode-1.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
     - ./datanode_entrypoint.sh:/datanode_entrypoint.sh
   entrypoint: ["/bin/bash", "/datanode_entrypoint.sh"]
   command: ["hdfs", "datanode"]


 hadoop-datanode-2:
   image: apache/hadoop:3.4.1
   container_name: hadoop-datanode-2
   hostname: hadoop-datanode-2
   user: "root"
   restart: always
   platform: linux/amd64
   deploy:
     resources:
       limits:
         cpus: "1.0"   # Ограничение использования CPU
         memory: "2g"  # Ограничение использования RAM
   shm_size: 10G
   depends_on:
     - hadoop-namenode
   ports:
     - "9865:9865"  # HTTP-порт для Web UI DataNode №2
     - "9971:9971"  # RPC порт для запросов от NameNode
   volumes:
     - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
     - ./config/hdfs-site-datanode-2.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
     - ./datanode_entrypoint.sh:/datanode_entrypoint.sh
   entrypoint: ["/bin/bash", "/datanode_entrypoint.sh"]
   command: ["hdfs", "datanode"]


 hadoop-datanode-3:
   image: apache/hadoop:3.4.1
   container_name: hadoop-datanode-3
   hostname: hadoop-datanode-3
   user: "root"
   restart: always
   platform: linux/amd64
   deploy:
     resources:
       limits:
         cpus: "1.0"   # Ограничение использования CPU
         memory: "2g"  # Ограничение использования RAM
   shm_size: 10G
   depends_on:
     - hadoop-namenode
   ports:
     - "9866:9866"  # HTTP-порт для Web UI DataNode №3
     - "9972:9972"  # RPC порт для запросов от NameNode
   volumes:
     - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
     - ./config/hdfs-site-datanode-3.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
     - ./datanode_entrypoint.sh:/datanode_entrypoint.sh
   entrypoint: ["/bin/bash", "/datanode_entrypoint.sh"]
   command: ["hdfs", "datanode"]


networks:
 confluent: